version: '3'

services:
  sn-curtain.com-api-production:
    image: registry.gitlab.com/sn-curtain/sn-curtain.com-api:latest
    container_name: sn-curtain.com-api-production
    restart: always
    ports:
      - 5602:5000
    environment:
      - NODE_ENV=staging
