version: '3'

networks:
  application-tier:

services:
  sn-curtain.com-api-staging:
    image: registry.gitlab.com/sn-curtain/sn-curtain.com-api:latest
    container_name: sn-curtain.com-api-staging
    restart: always
    ports:
      - 5601:5000
    environment:
      - NODE_ENV=staging
      - MONGO_URI=${MONGO_URI_STAG}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - SESSION_SCRET=${SESSION_SCRET}
      - FACEBOOK_CALLBACK_DEV=${FACEBOOK_CALLBACK_DEV}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_SECRET_ID=${FACEBOOK_SECRET_ID}
      - GOOGLE_CALLBACK_DEV=${GOOGLE_CALLBACK_DEV}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET_ID=${GOOGLE_SECRET_ID}
    networks:
      - application-tier

