version: "3"

services:
  sn-curtain.com-api-staging:
    image: registry.gitlab.com/sn-curtain/sn-curtain.com-api:latest
    container_name: sn-curtain.com-api-staging
    restart: always
    ports:
      - 5000
    environment:
      - VIRTUAL_PORT=dev.api.sn-curtain.com
      - VIRTUAL_PORT=5000
      - NODE_ENV=staging
      - MONGO_URI=${MONGO_URI_STAG}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - SESSION_SECRET=${SESSION_SCRET}
      - FACEBOOK_CALLBACK_STAG=${FACEBOOK_CALLBACK_STAG}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_SECRET_ID=${FACEBOOK_SECRET_ID}
      - GOOGLE_CALLBACK_STAG=${GOOGLE_CALLBACK_STAG}
      - GOOGLE_CLIENT_ID_STAG=${GOOGLE_CLIENT_ID_STAG}
      - GOOGLE_SECRET_ID_STAG=${GOOGLE_SECRET_ID_STAG}
      - FRONTEND_URI=${FRONTEND_URI_DEV}
      - COOKIE_SECRET=${COOKIE_SERCRET_DEV}
      - ENCRYPTION_SECRET_32=${ENCRYPTION_SECRET_32_GLOBAL}
      - ENCRYPTION_SECRET_64=${ENCRYPTION_SECRET_64_GLOBAL}
    networks:
      - application-tier

networks:
  ? application-tier
