version: "3"

services:
  sn-curtain.com-api-production:
    image: registry.gitlab.com/sn-curtain/sn-curtain.com-api:latest
    container_name: sn-curtain.com-api-production
    restart: always
    ports:
      - 5000
    environment:
      - VIRTUAL_PORT=api.sn-curtain.com
      - VIRTUAL_PORT=5000
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI_PROD}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - SESSION_SECRET=${SESSION_SCRET}
      - FACEBOOK_CALLBACK_PROD=${FACEBOOK_CALLBACK_PROD}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_SECRET_ID=${FACEBOOK_SECRET_ID}
      - GOOGLE_CALLBACK_PROD=${GOOGLE_CALLBACK_PROD}
      - GOOGLE_CLIENT_ID_PROD=${GOOGLE_CLIENT_ID_PROD}
      - GOOGLE_SECRET_ID_PROD=${GOOGLE_SECRET_ID_PROD}
      - FRONTEND_URI=${FRONTEND_URI_PROD}
      - COOKIE_SECRET=${COOKIE_SECRET_PROD}
      - ENCRYPTION_SECRET_32=${ENCRYPTION_SECRET_32_GLOBAL}
      - ENCRYPTION_SECRET_64=${ENCRYPTION_SECRET_64_GLOBAL}
    networks:
      - application-tier

networks:
  application-tier:
